# -*- coding: utf-8 -*-
import sys

# Form implementation generated from reading ui file 'resultinfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QTableWidgetItem

sys.path.append("./")
from service import service

class Ui_MainWindow(QMainWindow):
    def __init__(self):
        super(Ui_MainWindow, self).__init__()
        self.setupUi(self)
        self.setUp()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(766, 282)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./image/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 40, 761, 191))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 10, 61, 21))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(290, 10, 61, 21))
        self.comboBox.setObjectName("comboBox")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(510, 10, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(590, 10, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 10, 61, 21))
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(90, 10, 131, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(360, 10, 61, 21))
        self.label_8.setObjectName("label_8")
        self.comboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_5.setGeometry(QtCore.QRect(430, 10, 61, 21))
        self.comboBox_5.setObjectName("comboBox_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 766, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "学生成绩查询"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "编号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "学生编号"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "学生姓名"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "班级"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "科目"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "种类"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "成绩"))
        self.label.setText(_translate("MainWindow", "考试种类："))
        self.pushButton_3.setText(_translate("MainWindow", "查询"))
        self.pushButton_4.setText(_translate("MainWindow", "退出"))
        self.label_5.setText(_translate("MainWindow", "学生姓名："))
        self.label_8.setText(_translate("MainWindow", "考试科目："))

    def setUp(self):
        self.bingCbox()
        self.query()

        #绑定所有事件
        self.pushButton_3.clicked.connect(self.query)
        self.pushButton_4.clicked.connect(self.close)

    def bingCbox(self):
        result = service.query2("select DISTINCT  kindName from v_resultinfo")
        self.comboBox.addItem("所有")
        for i in result:
            self.comboBox.addItem(i[0])

        result = service.query2("select DISTINCT  subName from v_resultinfo")
        self.comboBox_5.addItem("所有")
        for i in result:
            self.comboBox_5.addItem(i[0])

    def query(self):
        self.tableWidget.setRowCount(0)
        self.tableWidget.clearContents()
        key = self.lineEdit_3.text()
        if key == "":
            if self.comboBox.currentText() == "所有":
                if self.comboBox_5.currentText() == "所有":
                    result = service.query2("select ID,stuID,stuName,concat(gradeName,className),subName,kindName,result from v_resultinfo")
                else:
                    result = service.query("select ID,stuID,stuName,concat(gradeName,className),subName,kindName,\
                    result from v_resultinfo where subName = %s",(self.comboBox_5.currentText(),))
            else:
                if self.comboBox_5.currentText() == "所有":
                    result = service.query("select ID,stuID,stuName,concat(gradeName,className),subName,kindName,\
                    result from v_resultinfo where kindName = %s",(self.comboBox.currentText(),))
                else:
                    result = service.query("select ID,stuID,stuName,concat(gradeName,className),subName,kindName,\
                    result from v_resultinfo where (subName = %s,kindName = %s)",(self.comboBox_5.currentText(),self.comboBox.currentText()))
        else:
            result = service.query2("select ID,stuID,stuName,concat(gradeName,className),subName,kindName,result from v_resultinfo where stuName like '%"+key+"%'")


        for i in range(len(result)):
            self.tableWidget.insertRow(i)
            for j in range(len(result[0])):
                data = QTableWidgetItem(str(result[i][j]))
                self.tableWidget.setItem(i,j,data)